///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoryModel {
/*
{
  "id": "708",
  "parent_id": "707",
  "category_name": "Parquet",
  "category_slug": "parquet",
  "sort": "1"
}
*/

  String? id;
  String? parentId;
  String? categoryName;
  String? categorySlug;
  String? sort;

  CategoryModel({
    this.id,
    this.parentId,
    this.categoryName,
    this.categorySlug,
    this.sort,
  });
  CategoryModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    parentId = json['parent_id']?.toString();
    categoryName = json['category_name']?.toString();
    categorySlug = json['category_slug']?.toString();
    sort = json['sort']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['parent_id'] = parentId;
    data['category_name'] = categoryName;
    data['category_slug'] = categorySlug;
    data['sort'] = sort;
    return data;
  }
}
