///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MessageModel {
/*
{
  "id": "2",
  "from_id": "97",
  "from_fullname": "Mikail  Karaaslan",
  "to_id": "57",
  "to_fullname": "Erkan  Alp",
  "message": "İyi Günler Erkan bey",
  "message_date": "2022-11-24 12:52:30",
  "is_read": "0",
  "read_date": null,
  "from_avatar": "",
  "to_avatar": "https://api.businessucces.com/uploads/profile/2023/01/10012023175717-1673369837.jpg"
} 
*/

  String? id;
  String? fromId;
  String? fromFullname;
  String? toId;
  String? toFullname;
  String? message;
  String? messageDate;
  String? isRead;
  String? readDate;
  String? fromAvatar;
  String? toAvatar;

  MessageModel({
    this.id,
    this.fromId,
    this.fromFullname,
    this.toId,
    this.toFullname,
    this.message,
    this.messageDate,
    this.isRead,
    this.readDate,
    this.fromAvatar,
    this.toAvatar,
  });
  MessageModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    fromId = json['from_id']?.toString();
    fromFullname = json['from_fullname']?.toString();
    toId = json['to_id']?.toString();
    toFullname = json['to_fullname']?.toString();
    message = json['message']?.toString();
    messageDate = json['message_date']?.toString();
    isRead = json['is_read']?.toString();
    readDate = json['read_date']?.toString();
    fromAvatar = json['from_avatar']?.toString();
    toAvatar = json['to_avatar']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['from_id'] = fromId;
    data['from_fullname'] = fromFullname;
    data['to_id'] = toId;
    data['to_fullname'] = toFullname;
    data['message'] = message;
    data['message_date'] = messageDate;
    data['is_read'] = isRead;
    data['read_date'] = readDate;
    data['from_avatar'] = fromAvatar;
    data['to_avatar'] = toAvatar;
    return data;
  }
}
