///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MessageDetailsModel {
/*
{
  "id": "7",
  "from_id": "57",
  "from_fullname": "Mehmet Can",
  "to_id": "97",
  "to_fullname": "ABC Firma LTD updated",
  "message": "Ek olarak kargo suresi hakkinda da bilgi verebilir misiniz?",
  "from_read": "1",
  "to_read": "0",
  "create_date": "2022-12-09 17:18:14",
  "from_avatar": "https://api.businessucces.com/uploads/profile/2023/01/10012023175717-1673369837.jpg",
  "to_avatar": ""
} 
*/

  String? id;
  String? fromId;
  String? fromFullname;
  String? toId;
  String? toFullname;
  String? message;
  String? fromRead;
  String? toRead;
  String? createDate;
  String? fromAvatar;
  String? toAvatar;

  MessageDetailsModel({
    this.id,
    this.fromId,
    this.fromFullname,
    this.toId,
    this.toFullname,
    this.message,
    this.fromRead,
    this.toRead,
    this.createDate,
    this.fromAvatar,
    this.toAvatar,
  });
  MessageDetailsModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    fromId = json['from_id']?.toString();
    fromFullname = json['from_fullname']?.toString();
    toId = json['to_id']?.toString();
    toFullname = json['to_fullname']?.toString();
    message = json['message']?.toString();
    fromRead = json['from_read']?.toString();
    toRead = json['to_read']?.toString();
    createDate = json['create_date']?.toString();
    fromAvatar = json['from_avatar']?.toString();
    toAvatar = json['to_avatar']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['from_id'] = fromId;
    data['from_fullname'] = fromFullname;
    data['to_id'] = toId;
    data['to_fullname'] = toFullname;
    data['message'] = message;
    data['from_read'] = fromRead;
    data['to_read'] = toRead;
    data['create_date'] = createDate;
    data['from_avatar'] = fromAvatar;
    data['to_avatar'] = toAvatar;
    return data;
  }
}
