///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CompanyDetailModelCollaborator {
/*
{
  "id": "5",
  "role": "admin",
  "name": "Fatih Sönmez",
  "photo": "https://api.businessucces.com/uploads/profile/2023/03/11032023095731-1678525051.png"
}
*/

  String? id;
  String? role;
  String? name;
  String? photo;

  CompanyDetailModelCollaborator({
    this.id,
    this.role,
    this.name,
    this.photo,
  });
  CompanyDetailModelCollaborator.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    role = json['role']?.toString();
    name = json['name']?.toString();
    photo = json['photo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['role'] = role;
    data['name'] = name;
    data['photo'] = photo;
    return data;
  }
}

class CompanyDetailModelSettings {
/*
{
  "language": "tr",
  "country": "TR",
  "timezone": "0.00"
}
*/

  String? language;
  String? country;
  String? timezone;

  CompanyDetailModelSettings({
    this.language,
    this.country,
    this.timezone,
  });
  CompanyDetailModelSettings.fromJson(Map<String, dynamic> json) {
    language = json['language']?.toString();
    country = json['country']?.toString();
    timezone = json['timezone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['language'] = language;
    data['country'] = country;
    data['timezone'] = timezone;
    return data;
  }
}

class CompanyDetailModelDistrict {
/*
{
  "id": "107622",
  "name": "Eyüpsultan"
}
*/

  String? id;
  String? name;

  CompanyDetailModelDistrict({
    this.id,
    this.name,
  });
  CompanyDetailModelDistrict.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class CompanyDetailModelCity {
/*
{
  "id": "2170",
  "name": "Istanbul"
}
*/

  String? id;
  String? name;

  CompanyDetailModelCity({
    this.id,
    this.name,
  });
  CompanyDetailModelCity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class CompanyDetailModelCountryTimezones {
/*
{
  "zoneName": "Europe/Istanbul",
  "gmtOffset": 10800,
  "gmtOffsetName": "UTC+03:00",
  "abbreviation": "EET",
  "tzName": "Eastern European Time"
}
*/

  String? zoneName;
  int? gmtOffset;
  String? gmtOffsetName;
  String? abbreviation;
  String? tzName;

  CompanyDetailModelCountryTimezones({
    this.zoneName,
    this.gmtOffset,
    this.gmtOffsetName,
    this.abbreviation,
    this.tzName,
  });
  CompanyDetailModelCountryTimezones.fromJson(Map<String, dynamic> json) {
    zoneName = json['zoneName']?.toString();
    gmtOffset = json['gmtOffset']?.toInt();
    gmtOffsetName = json['gmtOffsetName']?.toString();
    abbreviation = json['abbreviation']?.toString();
    tzName = json['tzName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['zoneName'] = zoneName;
    data['gmtOffset'] = gmtOffset;
    data['gmtOffsetName'] = gmtOffsetName;
    data['abbreviation'] = abbreviation;
    data['tzName'] = tzName;
    return data;
  }
}

class CompanyDetailModelCountry {
/*
{
  "id": "225",
  "name": "Turkey",
  "code": "TR",
  "phonecode": "90",
  "currency": "TRY",
  "currency_name": "Turkish lira",
  "currency_symbol": "₺",
  "timezones": [
    {
      "zoneName": "Europe/Istanbul",
      "gmtOffset": 10800,
      "gmtOffsetName": "UTC+03:00",
      "abbreviation": "EET",
      "tzName": "Eastern European Time"
    }
  ],
  "flag": "🇹🇷"
}
*/

  String? id;
  String? name;
  String? code;
  String? phonecode;
  String? currency;
  String? currencyName;
  String? currencySymbol;
  List<CompanyDetailModelCountryTimezones?>? timezones;
  String? flag;

  CompanyDetailModelCountry({
    this.id,
    this.name,
    this.code,
    this.phonecode,
    this.currency,
    this.currencyName,
    this.currencySymbol,
    this.timezones,
    this.flag,
  });
  CompanyDetailModelCountry.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
    phonecode = json['phonecode']?.toString();
    currency = json['currency']?.toString();
    currencyName = json['currency_name']?.toString();
    currencySymbol = json['currency_symbol']?.toString();
    if (json['timezones'] != null) {
      final v = json['timezones'];
      final arr0 = <CompanyDetailModelCountryTimezones>[];
      v.forEach((v) {
        arr0.add(CompanyDetailModelCountryTimezones.fromJson(v));
      });
      timezones = arr0;
    }
    flag = json['flag']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['code'] = code;
    data['phonecode'] = phonecode;
    data['currency'] = currency;
    data['currency_name'] = currencyName;
    data['currency_symbol'] = currencySymbol;
    if (timezones != null) {
      final v = timezones;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['timezones'] = arr0;
    }
    data['flag'] = flag;
    return data;
  }
}

class CompanyDetailModel {
/*
{
  "id": "6",
  "name": "Voiser",
  "tax_office": "Büyük Mükellefler",
  "tax_number": "12312312312",
  "phone": "9005313505477",
  "email": "bilgi@fsdigital.co",
  "country": {
    "id": "225",
    "name": "Turkey",
    "code": "TR",
    "phonecode": "90",
    "currency": "TRY",
    "currency_name": "Turkish lira",
    "currency_symbol": "₺",
    "timezones": [
      {
        "zoneName": "Europe/Istanbul",
        "gmtOffset": 10800,
        "gmtOffsetName": "UTC+03:00",
        "abbreviation": "EET",
        "tzName": "Eastern European Time"
      }
    ],
    "flag": "🇹🇷"
  },
  "city": {
    "id": "2170",
    "name": "Istanbul"
  },
  "district": {
    "id": "107622",
    "name": "Eyüpsultan"
  },
  "address": "İstanbul",
  "postal_code": "34040",
  "logo": "https://api.businessucces.com/uploads/logos/2023/03/11032023100752-1678525672.png",
  "cover": "",
  "about": "Voice Creation Platform!",
  "settings": {
    "language": "tr",
    "country": "TR",
    "timezone": "0.00"
  },
  "registration_date": "2023-03-11 10:06:34",
  "collaborator": [
    {
      "id": "5",
      "role": "admin",
      "name": "Fatih Sönmez",
      "photo": "https://api.businessucces.com/uploads/profile/2023/03/11032023095731-1678525051.png"
    }
  ]
}
*/

  String? id;
  String? name;
  String? taxOffice;
  String? taxNumber;
  String? phone;
  String? email;
  CompanyDetailModelCountry? country;
  CompanyDetailModelCity? city;
  CompanyDetailModelDistrict? district;
  String? address;
  String? postalCode;
  String? logo;
  String? cover;
  String? about;
  CompanyDetailModelSettings? settings;
  String? registrationDate;
  List<CompanyDetailModelCollaborator?>? collaborator;

  CompanyDetailModel({
    this.id,
    this.name,
    this.taxOffice,
    this.taxNumber,
    this.phone,
    this.email,
    this.country,
    this.city,
    this.district,
    this.address,
    this.postalCode,
    this.logo,
    this.cover,
    this.about,
    this.settings,
    this.registrationDate,
    this.collaborator,
  });
  CompanyDetailModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    taxOffice = json['tax_office']?.toString();
    taxNumber = json['tax_number']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    country = (json['country'] != null)
        ? CompanyDetailModelCountry.fromJson(json['country'])
        : null;
    city = (json['city'] != null)
        ? CompanyDetailModelCity.fromJson(json['city'])
        : null;
    district = (json['district'] != null)
        ? CompanyDetailModelDistrict.fromJson(json['district'])
        : null;
    address = json['address']?.toString();
    postalCode = json['postal_code']?.toString();
    logo = json['logo']?.toString();
    cover = json['cover']?.toString();
    about = json['about']?.toString();
    settings = (json['settings'] != null)
        ? CompanyDetailModelSettings.fromJson(json['settings'])
        : null;
    registrationDate = json['registration_date']?.toString();
    if (json['collaborator'] != null) {
      final v = json['collaborator'];
      final arr0 = <CompanyDetailModelCollaborator>[];
      v.forEach((v) {
        arr0.add(CompanyDetailModelCollaborator.fromJson(v));
      });
      collaborator = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['tax_office'] = taxOffice;
    data['tax_number'] = taxNumber;
    data['phone'] = phone;
    data['email'] = email;
    if (country != null) {
      data['country'] = country!.toJson();
    }
    if (city != null) {
      data['city'] = city!.toJson();
    }
    if (district != null) {
      data['district'] = district!.toJson();
    }
    data['address'] = address;
    data['postal_code'] = postalCode;
    data['logo'] = logo;
    data['cover'] = cover;
    data['about'] = about;
    if (settings != null) {
      data['settings'] = settings!.toJson();
    }
    data['registration_date'] = registrationDate;
    if (collaborator != null) {
      final v = collaborator;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['collaborator'] = arr0;
    }
    return data;
  }
}
