///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CompanyModel2 {
/*
{
  "id": "34",
  "name": "ABC Firma LTD",
  "logo": "",
  "cover": "",
  "role": "admin",
  "is_approved": "yes"
}
*/

  String? id;
  String? name;
  String? logo;
  String? cover;
  String? role;
  String? isApproved;

  CompanyModel2({
    this.id,
    this.name,
    this.logo,
    this.cover,
    this.role,
    this.isApproved,
  });
  CompanyModel2.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    logo = json['logo']?.toString();
    cover = json['cover']?.toString();
    role = json['role']?.toString();
    isApproved = json['is_approved']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['logo'] = logo;
    data['cover'] = cover;
    data['role'] = role;
    data['is_approved'] = isApproved;
    return data;
  }
}
