///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BasketModelProductImageMeta {
/*
{
  "name": "image_picker4802436063087939591.jpg",
  "type": "application/octet-stream",
  "error": 0,
  "size": 49789
} 
*/

  String? name;
  String? type;
  int? error;
  int? size;

  BasketModelProductImageMeta({
    this.name,
    this.type,
    this.error,
    this.size,
  });
  BasketModelProductImageMeta.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
    error = json['error']?.toInt();
    size = json['size']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    data['error'] = error;
    data['size'] = size;
    return data;
  }
}

class BasketModelProductImage {
/*
{
  "path": "uploads/posts/2023/03/04032023104621-1677923181.jpg",
  "meta": {
    "name": "image_picker4802436063087939591.jpg",
    "type": "application/octet-stream",
    "error": 0,
    "size": 49789
  },
  "url": "https://api.businessucces.com/uploads/posts/2023/03/04032023104621-1677923181.jpg"
} 
*/

  String? path;
  BasketModelProductImageMeta? meta;
  String? url;

  BasketModelProductImage({
    this.path,
    this.meta,
    this.url,
  });
  BasketModelProductImage.fromJson(Map<String, dynamic> json) {
    path = json['path']?.toString();
    meta = (json['meta'] != null) ? BasketModelProductImageMeta.fromJson(json['meta']) : null;
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['path'] = path;
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    data['url'] = url;
    return data;
  }
}

class BasketModelProduct {
/*
{
  "id": "3440",
  "account_id": "56",
  "user_id": "57",
  "product_name": "ürün",
  "product_description": "ürün",
  "product_summary": "ürün",
  "brand": "1",
  "price": "100.00",
  "currency": "USD",
  "status": "1",
  "image": [
    {
      "path": "uploads/posts/2023/03/04032023104621-1677923181.jpg",
      "meta": {
        "name": "image_picker4802436063087939591.jpg",
        "type": "application/octet-stream",
        "error": 0,
        "size": 49789
      },
      "url": "https://api.businessucces.com/uploads/posts/2023/03/04032023104621-1677923181.jpg"
    }
  ]
} 
*/

  String? id;
  String? accountId;
  String? userId;
  String? productName;
  String? productDescription;
  String? productSummary;
  String? brand;
  String? price;
  String? currency;
  String? status;
  List<BasketModelProductImage?>? image;

  BasketModelProduct({
    this.id,
    this.accountId,
    this.userId,
    this.productName,
    this.productDescription,
    this.productSummary,
    this.brand,
    this.price,
    this.currency,
    this.status,
    this.image,
  });
  BasketModelProduct.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    accountId = json['account_id']?.toString();
    userId = json['user_id']?.toString();
    productName = json['product_name']?.toString();
    productDescription = json['product_description']?.toString();
    productSummary = json['product_summary']?.toString();
    brand = json['brand']?.toString();
    price = json['price']?.toString();
    currency = json['currency']?.toString();
    status = json['status']?.toString();
  if (json['image'] != null) {
  final v = json['image'];
  final arr0 = <BasketModelProductImage>[];
  v.forEach((v) {
  arr0.add(BasketModelProductImage.fromJson(v));
  });
    image = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['account_id'] = accountId;
    data['user_id'] = userId;
    data['product_name'] = productName;
    data['product_description'] = productDescription;
    data['product_summary'] = productSummary;
    data['brand'] = brand;
    data['price'] = price;
    data['currency'] = currency;
    data['status'] = status;
    if (image != null) {
      final v = image;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['image'] = arr0;
    }
    return data;
  }
}

class BasketModel {
/*
{
  "id": "639",
  "user_id": "57",
  "product_id": "3440",
  "quantity": "5",
  "create_date": "2023-01-06 04:12:11",
  "product": {
    "id": "3440",
    "account_id": "56",
    "user_id": "57",
    "product_name": "ürün",
    "product_description": "ürün",
    "product_summary": "ürün",
    "brand": "1",
    "price": "100.00",
    "currency": "USD",
    "status": "1",
    "image": [
      {
        "path": "uploads/posts/2023/03/04032023104621-1677923181.jpg",
        "meta": {
          "name": "image_picker4802436063087939591.jpg",
          "type": "application/octet-stream",
          "error": 0,
          "size": 49789
        },
        "url": "https://api.businessucces.com/uploads/posts/2023/03/04032023104621-1677923181.jpg"
      }
    ]
  }
} 
*/

  String? id;
  String? userId;
  String? productId;
  String? quantity;
  String? createDate;
  BasketModelProduct? product;

  BasketModel({
    this.id,
    this.userId,
    this.productId,
    this.quantity,
    this.createDate,
    this.product,
  });
  BasketModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    userId = json['user_id']?.toString();
    productId = json['product_id']?.toString();
    quantity = json['quantity']?.toString();
    createDate = json['create_date']?.toString();
    product = (json['product'] != null) ? BasketModelProduct.fromJson(json['product']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = userId;
    data['product_id'] = productId;
    data['quantity'] = quantity;
    data['create_date'] = createDate;
    if (product != null) {
      data['product'] = product!.toJson();
    }
    return data;
  }
}
