///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FeedModelCommentsCommentsUser {
/*
{
  "id": "408",
  "type": "personal",
  "username": "user_408",
  "name": " ",
  "photo": "https://api.businessucces.com/uploads/profile/2023/01/15012023203949-1673811589.png",
  "cover": ""
} 
*/

  String? id;
  String? type;
  String? username;
  String? name;
  String? photo;
  String? cover;

  FeedModelCommentsCommentsUser({
    this.id,
    this.type,
    this.username,
    this.name,
    this.photo,
    this.cover,
  });
  FeedModelCommentsCommentsUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    type = json['type']?.toString();
    username = json['username']?.toString();
    name = json['name']?.toString();
    photo = json['photo']?.toString();
    cover = json['cover']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['username'] = username;
    data['name'] = name;
    data['photo'] = photo;
    data['cover'] = cover;
    return data;
  }
}

class FeedModelCommentsComments {
/*
{
  "id": "51",
  "user": {
    "id": "408",
    "type": "personal",
    "username": "user_408",
    "name": " ",
    "photo": "https://api.businessucces.com/uploads/profile/2023/01/15012023203949-1673811589.png",
    "cover": ""
  },
  "create_date": "2023-01-09 21:29:18",
  "content": "görüşlerinizi iletin"
} 
*/

  String? id;
  FeedModelCommentsCommentsUser? user;
  String? createDate;
  String? content;

  FeedModelCommentsComments({
    this.id,
    this.user,
    this.createDate,
    this.content,
  });
  FeedModelCommentsComments.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    user = (json['user'] != null)
        ? FeedModelCommentsCommentsUser.fromJson(json['user'])
        : null;
    createDate = json['create_date']?.toString();
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['create_date'] = createDate;
    data['content'] = content;
    return data;
  }
}

class FeedModelComments {
/*
{
  "total": 0,
  "offset": 0,
  "comments": [
    {
      "id": "51",
      "user": {
        "id": "408",
        "type": "personal",
        "username": "user_408",
        "name": " ",
        "photo": "https://api.businessucces.com/uploads/profile/2023/01/15012023203949-1673811589.png",
        "cover": ""
      },
      "create_date": "2023-01-09 21:29:18",
      "content": "görüşlerinizi iletin"
    }
  ]
} 
*/

  int? total;
  int? offset;
  List<FeedModelCommentsComments?>? comments;

  FeedModelComments({
    this.total,
    this.offset,
    this.comments,
  });
  FeedModelComments.fromJson(Map<String, dynamic> json) {
    total = json['total']?.toInt();
    offset = json['offset']?.toInt();
    if (json['comments'] != null) {
      final v = json['comments'];
      final arr0 = <FeedModelCommentsComments>[];
      v.forEach((v) {
        arr0.add(FeedModelCommentsComments.fromJson(v));
      });
      comments = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['total'] = total;
    data['offset'] = offset;
    if (comments != null) {
      final v = comments;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['comments'] = arr0;
    }
    return data;
  }
}

class FeedModelImagesMeta {
  String? name;
  String? type;
  int? error;
  int? size;

  FeedModelImagesMeta({
    this.name,
    this.type,
    this.error,
    this.size,
  });
  FeedModelImagesMeta.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
    error = json['error']?.toInt();
    size = json['size']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    data['error'] = error;
    data['size'] = size;
    return data;
  }
}

class FeedModelImages {
  String? path;
  FeedModelImagesMeta? meta;
  String? url;

  FeedModelImages({
    this.path,
    this.meta,
    this.url,
  });
  FeedModelImages.fromJson(Map<String, dynamic> json) {
    path = json['path']?.toString();
    meta = (json['meta'] != null)
        ? FeedModelImagesMeta.fromJson(json['meta'])
        : null;
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['path'] = path;
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    data['url'] = url;
    return data;
  }
}

class FeedModelUser {
  String? id;
  String? type;
  String? username;
  String? name;
  String? photo;
  String? cover;

  FeedModelUser({
    this.id,
    this.type,
    this.username,
    this.name,
    this.photo,
    this.cover,
  });
  FeedModelUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    type = json['type']?.toString();
    username = json['username']?.toString();
    name = json['name']?.toString();
    photo = json['photo']?.toString();
    cover = json['cover']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['username'] = username;
    data['name'] = name;
    data['photo'] = photo;
    data['cover'] = cover;
    return data;
  }
}

class FeedModel {
  String? id;
  String? type;
  String? createDate;
  FeedModelUser? user;
  String? content;
  List<FeedModelImages?>? images;
  String? videos;
  FeedModelComments? comments;
  int? likes;
  bool? likeStatus;

  FeedModel({
    this.id,
    this.type,
    this.createDate,
    this.user,
    this.content,
    this.images,
    this.videos,
    this.comments,
    this.likes,
    this.likeStatus,
  });
  FeedModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    type = json['type']?.toString();
    createDate = json['create_date']?.toString();
    user = (json['user'] != null) ? FeedModelUser.fromJson(json['user']) : null;
    content = json['content']?.toString();
    if (json['images'] != null) {
      final v = json['images'];
      final arr0 = <FeedModelImages>[];
      v.forEach((v) {
        arr0.add(FeedModelImages.fromJson(v));
      });
      images = arr0;
    }
    videos = json['videos']?.toString();
    comments = (json['comments'] != null)
        ? FeedModelComments.fromJson(json['comments'])
        : null;
    likes = json['likes']?.toInt();
    likeStatus = json['like_status'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['create_date'] = createDate;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['content'] = content;
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['images'] = arr0;
    }
    data['videos'] = videos;
    if (comments != null) {
      data['comments'] = comments!.toJson();
    }
    data['likes'] = likes;
    data['like_status'] = likeStatus;
    return data;
  }
}
