///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PersonalProfileModelCompanies {
/*
{
  "id": "99",
  "role": "admin",
  "name": "company name up",
  "logo": "https://api.businessucces.com/uploads/logos/2023/01/22012023122737-1674386857.jpg"
} 
*/

  String? id;
  String? role;
  String? name;
  String? logo;

  PersonalProfileModelCompanies({
    this.id,
    this.role,
    this.name,
    this.logo,
  });
  PersonalProfileModelCompanies.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    role = json['role']?.toString();
    name = json['name']?.toString();
    logo = json['logo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['role'] = role;
    data['name'] = name;
    data['logo'] = logo;
    return data;
  }
}

class PersonalProfileModelSettings {
/*
{
  "language": "en",
  "country": "",
  "timezone": "-5.00"
} 
*/

  String? language;
  String? country;
  String? timezone;

  PersonalProfileModelSettings({
    this.language,
    this.country,
    this.timezone,
  });
  PersonalProfileModelSettings.fromJson(Map<String, dynamic> json) {
    language = json['language']?.toString();
    country = json['country']?.toString();
    timezone = json['timezone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['language'] = language;
    data['country'] = country;
    data['timezone'] = timezone;
    return data;
  }
}

class PersonalProfileModelDistrict {
/*
{
  "id": "45",
  "name": "Reef Al Fujairah City"
} 
*/

  String? id;
  String? name;

  PersonalProfileModelDistrict({
    this.id,
    this.name,
  });
  PersonalProfileModelDistrict.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class PersonalProfileModelCity {
/*
{
  "id": "34",
  "name": "Kunene Region"
} 
*/

  String? id;
  String? name;

  PersonalProfileModelCity({
    this.id,
    this.name,
  });
  PersonalProfileModelCity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class PersonalProfileModelCountryTimezones {
/*
{
  "zoneName": "America/Adak",
  "gmtOffset": -36000,
  "gmtOffsetName": "UTC-10:00",
  "abbreviation": "HST",
  "tzName": "Hawaii–Aleutian Standard Time"
} 
*/

  String? zoneName;
  int? gmtOffset;
  String? gmtOffsetName;
  String? abbreviation;
  String? tzName;

  PersonalProfileModelCountryTimezones({
    this.zoneName,
    this.gmtOffset,
    this.gmtOffsetName,
    this.abbreviation,
    this.tzName,
  });
  PersonalProfileModelCountryTimezones.fromJson(Map<String, dynamic> json) {
    zoneName = json['zoneName']?.toString();
    gmtOffset = json['gmtOffset']?.toInt();
    gmtOffsetName = json['gmtOffsetName']?.toString();
    abbreviation = json['abbreviation']?.toString();
    tzName = json['tzName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['zoneName'] = zoneName;
    data['gmtOffset'] = gmtOffset;
    data['gmtOffsetName'] = gmtOffsetName;
    data['abbreviation'] = abbreviation;
    data['tzName'] = tzName;
    return data;
  }
}

class PersonalProfileModelCountry {
/*
{
  "id": "233",
  "name": "United States",
  "code": "US",
  "phonecode": "1",
  "currency": "USD",
  "currency_name": "United States dollar",
  "currency_symbol": "$",
  "timezones": [
    {
      "zoneName": "America/Adak",
      "gmtOffset": -36000,
      "gmtOffsetName": "UTC-10:00",
      "abbreviation": "HST",
      "tzName": "Hawaii–Aleutian Standard Time"
    }
  ],
  "flag": "🇺🇸"
} 
*/

  String? id;
  String? name;
  String? code;
  String? phonecode;
  String? currency;
  String? currencyName;
  String? currencySymbol;
  List<PersonalProfileModelCountryTimezones?>? timezones;
  String? flag;

  PersonalProfileModelCountry({
    this.id,
    this.name,
    this.code,
    this.phonecode,
    this.currency,
    this.currencyName,
    this.currencySymbol,
    this.timezones,
    this.flag,
  });
  PersonalProfileModelCountry.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
    phonecode = json['phonecode']?.toString();
    currency = json['currency']?.toString();
    currencyName = json['currency_name']?.toString();
    currencySymbol = json['currency_symbol']?.toString();
  if (json['timezones'] != null) {
  final v = json['timezones'];
  final arr0 = <PersonalProfileModelCountryTimezones>[];
  v.forEach((v) {
  arr0.add(PersonalProfileModelCountryTimezones.fromJson(v));
  });
    timezones = arr0;
    }
    flag = json['flag']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['code'] = code;
    data['phonecode'] = phonecode;
    data['currency'] = currency;
    data['currency_name'] = currencyName;
    data['currency_symbol'] = currencySymbol;
    if (timezones != null) {
      final v = timezones;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['timezones'] = arr0;
    }
    data['flag'] = flag;
    return data;
  }
}

class PersonalProfileModel {
/*
{
  "id": "93",
  "name": " ",
  "photo": "https://api.businessucces.com/uploads/profile/2023/02/05022023104627-1675590387.jpg",
  "cover": "https://api.businessucces.com/uploads/covers/2023/01/14012023223252-1673731972.jpg",
  "phone": "",
  "email": "test100.personal@gmail.com",
  "citizenship_number": "",
  "tax_office": "",
  "tax_number": "0",
  "gender": "Unknown",
  "country": {
    "id": "233",
    "name": "United States",
    "code": "US",
    "phonecode": "1",
    "currency": "USD",
    "currency_name": "United States dollar",
    "currency_symbol": "$",
    "timezones": [
      {
        "zoneName": "America/Adak",
        "gmtOffset": -36000,
        "gmtOffsetName": "UTC-10:00",
        "abbreviation": "HST",
        "tzName": "Hawaii–Aleutian Standard Time"
      }
    ],
    "flag": "🇺🇸"
  },
  "city": {
    "id": "34",
    "name": "Kunene Region"
  },
  "district": {
    "id": "45",
    "name": "Reef Al Fujairah City"
  },
  "address": "",
  "postal_code": "",
  "about": "",
  "settings": {
    "language": "en",
    "country": "",
    "timezone": "-5.00"
  },
  "registration_date": "2022-11-18 17:38:22",
  "companies": [
    {
      "id": "99",
      "role": "admin",
      "name": "company name up",
      "logo": "https://api.businessucces.com/uploads/logos/2023/01/22012023122737-1674386857.jpg"
    }
  ]
} 
*/

  String? id;
  String? name;
  String? photo;
  String? cover;
  String? phone;
  String? email;
  String? citizenshipNumber;
  String? taxOffice;
  String? taxNumber;
  String? gender;
  PersonalProfileModelCountry? country;
  PersonalProfileModelCity? city;
  PersonalProfileModelDistrict? district;
  String? address;
  String? postalCode;
  String? about;
  PersonalProfileModelSettings? settings;
  String? registrationDate;
  List<PersonalProfileModelCompanies?>? companies;

  PersonalProfileModel({
    this.id,
    this.name,
    this.photo,
    this.cover,
    this.phone,
    this.email,
    this.citizenshipNumber,
    this.taxOffice,
    this.taxNumber,
    this.gender,
    this.country,
    this.city,
    this.district,
    this.address,
    this.postalCode,
    this.about,
    this.settings,
    this.registrationDate,
    this.companies,
  });
  PersonalProfileModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    photo = json['photo']?.toString();
    cover = json['cover']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    citizenshipNumber = json['citizenship_number']?.toString();
    taxOffice = json['tax_office']?.toString();
    taxNumber = json['tax_number']?.toString();
    gender = json['gender']?.toString();
    country = (json['country'] != null) ? PersonalProfileModelCountry.fromJson(json['country']) : null;
    city = (json['city'] != null) ? PersonalProfileModelCity.fromJson(json['city']) : null;
    district = (json['district'] != null) ? PersonalProfileModelDistrict.fromJson(json['district']) : null;
    address = json['address']?.toString();
    postalCode = json['postal_code']?.toString();
    about = json['about']?.toString();
    settings = (json['settings'] != null) ? PersonalProfileModelSettings.fromJson(json['settings']) : null;
    registrationDate = json['registration_date']?.toString();
  if (json['companies'] != null) {
  final v = json['companies'];
  final arr0 = <PersonalProfileModelCompanies>[];
  v.forEach((v) {
  arr0.add(PersonalProfileModelCompanies.fromJson(v));
  });
    companies = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['photo'] = photo;
    data['cover'] = cover;
    data['phone'] = phone;
    data['email'] = email;
    data['citizenship_number'] = citizenshipNumber;
    data['tax_office'] = taxOffice;
    data['tax_number'] = taxNumber;
    data['gender'] = gender;
    if (country != null) {
      data['country'] = country!.toJson();
    }
    if (city != null) {
      data['city'] = city!.toJson();
    }
    if (district != null) {
      data['district'] = district!.toJson();
    }
    data['address'] = address;
    data['postal_code'] = postalCode;
    data['about'] = about;
    if (settings != null) {
      data['settings'] = settings!.toJson();
    }
    data['registration_date'] = registrationDate;
    if (companies != null) {
      final v = companies;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['companies'] = arr0;
    }
    return data;
  }
}
