///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductModelImagesMeta {
/*
{
  "name": "image_picker4802436063087939591.jpg",
  "type": "application/octet-stream",
  "error": 0,
  "size": 49789
} 
*/

  String? name;
  String? type;
  int? error;
  int? size;

  ProductModelImagesMeta({
    this.name,
    this.type,
    this.error,
    this.size,
  });
  ProductModelImagesMeta.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    type = json['type']?.toString();
    error = json['error']?.toInt();
    size = json['size']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['type'] = type;
    data['error'] = error;
    data['size'] = size;
    return data;
  }
}

class ProductModelImages {
/*
{
  "path": "uploads/posts/2023/03/04032023104621-1677923181.jpg",
  "meta": {
    "name": "image_picker4802436063087939591.jpg",
    "type": "application/octet-stream",
    "error": 0,
    "size": 49789
  },
  "url": "https://api.businessucces.com/uploads/posts/2023/03/04032023104621-1677923181.jpg"
} 
*/

  String? path;
  ProductModelImagesMeta? meta;
  String? url;

  ProductModelImages({
    this.path,
    this.meta,
    this.url,
  });
  ProductModelImages.fromJson(Map<String, dynamic> json) {
    path = json['path']?.toString();
    meta = (json['meta'] != null) ? ProductModelImagesMeta.fromJson(json['meta']) : null;
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['path'] = path;
    if (meta != null) {
      data['meta'] = meta!.toJson();
    }
    data['url'] = url;
    return data;
  }
}

class ProductModelBrand {
/*
{
  "id": "24",
  "name": "Deneme Brand"
} 
*/

  String? id;
  String? name;

  ProductModelBrand({
    this.id,
    this.name,
  });
  ProductModelBrand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ProductModelDescription {
/*
{
  "en": "Test Product Description",
  "tr": "Deneme Ürün  Açıklaması",
  "de": "Deneme Ürün  Açıklaması"
} 
*/

  String? en;
  String? tr;
  String? de;

  ProductModelDescription({
    this.en,
    this.tr,
    this.de,
  });
  ProductModelDescription.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductModelSummary {
/*
{
  "en": "Test Product Summary",
  "tr": "Deneme Ürün Özeti",
  "de": "Deneme Ürün Özeti"
} 
*/

  String? en;
  String? tr;
  String? de;

  ProductModelSummary({
    this.en,
    this.tr,
    this.de,
  });
  ProductModelSummary.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductModelName {
/*
{
  "en": "Test Product",
  "tr": "Deneme Ürünü",
  "de": "Deneme Ürünü"
} 
*/

  String? en;
  String? tr;
  String? de;

  ProductModelName({
    this.en,
    this.tr,
    this.de,
  });
  ProductModelName.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductModel {
/*
{
  "id": "3364",
  "product_type": "",
  "name": {
    "en": "Test Product",
    "tr": "Deneme Ürünü",
    "de": "Deneme Ürünü"
  },
  "summary": {
    "en": "Test Product Summary",
    "tr": "Deneme Ürün Özeti",
    "de": "Deneme Ürün Özeti"
  },
  "description": {
    "en": "Test Product Description",
    "tr": "Deneme Ürün  Açıklaması",
    "de": "Deneme Ürün  Açıklaması"
  },
  "brand": {
    "id": "24",
    "name": "Deneme Brand"
  },
  "price": "100.00",
  "currency": "TRY",
  "images": [
    {
      "path": "uploads/posts/2023/03/04032023104621-1677923181.jpg",
      "meta": {
        "name": "image_picker4802436063087939591.jpg",
        "type": "application/octet-stream",
        "error": 0,
        "size": 49789
      },
      "url": "https://api.businessucces.com/uploads/posts/2023/03/04032023104621-1677923181.jpg"
    }
  ]
} 
*/

  String? id;
  String? productType;
  ProductModelName? name;
  ProductModelSummary? summary;
  ProductModelDescription? description;
  ProductModelBrand? brand;
  String? price;
  String? currency;
  List<ProductModelImages?>? images;

  ProductModel({
    this.id,
    this.productType,
    this.name,
    this.summary,
    this.description,
    this.brand,
    this.price,
    this.currency,
    this.images,
  });
  ProductModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    productType = json['product_type']?.toString();
    name = (json['name'] != null) ? ProductModelName.fromJson(json['name']) : null;
    summary = (json['summary'] != null) ? ProductModelSummary.fromJson(json['summary']) : null;
    description = (json['description'] != null) ? ProductModelDescription.fromJson(json['description']) : null;
    brand = (json['brand'] != null) ? ProductModelBrand.fromJson(json['brand']) : null;
    price = json['price']?.toString();
    currency = json['currency']?.toString();
  if (json['images'] != null) {
  final v = json['images'];
  final arr0 = <ProductModelImages>[];
  v.forEach((v) {
  arr0.add(ProductModelImages.fromJson(v));
  });
    images = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['product_type'] = productType;
    if (name != null) {
      data['name'] = name!.toJson();
    }
    if (summary != null) {
      data['summary'] = summary!.toJson();
    }
    if (description != null) {
      data['description'] = description!.toJson();
    }
    if (brand != null) {
      data['brand'] = brand!.toJson();
    }
    data['price'] = price;
    data['currency'] = currency;
    if (images != null) {
      final v = images;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['images'] = arr0;
    }
    return data;
  }
}
