// ignore_for_file: public_member_api_docs, sort_constructors_first
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VersionModelAndroid {
/*
{
  "version": "10",
  "url": "https://play.google.com/store/apps/details?id=com.b2geta.b2geta_mobile"
} 
*/

  String? version;
  String? url;

  VersionModelAndroid({
    this.version,
    this.url,
  });
  VersionModelAndroid.fromJson(Map<String, dynamic> json) {
    version = json['version']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['version'] = version;
    data['url'] = url;
    return data;
  }

  @override
  String toString() => 'VersionModelAndroid(version: $version, url: $url)';
}

class VersionModelIos {
/*
{
  "version": "10",
  "url": "https://apps.apple.com/tr/app/b2geta/id6449490439"
} 
*/

  String? version;
  String? url;

  VersionModelIos({
    this.version,
    this.url,
  });
  VersionModelIos.fromJson(Map<String, dynamic> json) {
    version = json['version']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['version'] = version;
    data['url'] = url;
    return data;
  }

  @override
  String toString() => 'VersionModelIos(version: $version, url: $url)';
}

class VersionModel {
/*
{
  "title": "B2Geta",
  "endpoint": "https://api.b2geta.com/",
  "ios": {
    "version": "10",
    "url": "https://apps.apple.com/tr/app/b2geta/id6449490439"
  },
  "android": {
    "version": "10",
    "url": "https://play.google.com/store/apps/details?id=com.b2geta.b2geta_mobile"
  }
} 
*/

  String? title;
  String? endpoint;
  VersionModelIos? ios;
  VersionModelAndroid? android;

  VersionModel({
    this.title,
    this.endpoint,
    this.ios,
    this.android,
  });
  VersionModel.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    endpoint = json['endpoint']?.toString();
    ios = (json['ios'] != null) ? VersionModelIos.fromJson(json['ios']) : null;
    android = (json['android'] != null)
        ? VersionModelAndroid.fromJson(json['android'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['endpoint'] = endpoint;
    if (ios != null) {
      data['ios'] = ios!.toJson();
    }
    if (android != null) {
      data['android'] = android!.toJson();
    }
    return data;
  }

  @override
  String toString() =>
      'VersionModel(title: $title, endpoint: $endpoint versionModelIos:$ios versionModelAndroid: $android)';
}
