import 'package:get/get.dart';

class AppLanguages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          // LANGUAGE PAGE
          'Language Selection': 'Language Selection',
          'Save': 'Save',
          // LOGIN PAGE
          'Member Login': 'Member Login',
          'E-mail': 'E-mail',
          'Password': 'Password',
          'Remember me:': 'Remember me',
          'Forgot Password': 'I forgot my password',
          'Login': 'Login',
          'Sign Up': 'Sign Up',
          'About Us': 'About Us',
          'Privacy': 'Privacy',
          'Terms and Conditions': 'Terms and Conditions',
          'Contact': 'Contact',
          'Copyright': 'Copyright 2022 B2Geta. All rights reserved',
          'E-mail Validate-1': 'Please enter your email address',
          'E-mail Validate-2': 'Please enter a valid email address',
          'Password Validate-1': 'Please enter your password',
          'Password Validate-2':
              'Password must be at least 8 characters in length',
          'Login Error': 'Invalid Email or Password',
          'Close': 'Close',
          // REGISTER PAGE
          'Create Account': 'Create Account',
          'E-mail (confirm)': 'E-mail (confirm)',
          'Password (confirm)': 'Password (confirm)',
          'Company Name': 'Company Name',
          'Official Person': 'Official Person',
          'Official Phone': 'Official Phone',
          'Country': 'Country',
          "Country Dropdown": 'Search country...',
          'User Agreement': 'I have read and accept the user agreement',
          'E-mail Validate-3': 'Unmatched email address',
          'Password Validate-3': 'Unmatched password',
          'Company Name Validate': 'Please enter a company name',
          'Register Alert-1': 'Registration Successful',
          'Register Alert-2': 'Check Your Information',
          // NAVIGATION PAGE
          'Homepage': 'Homepage',
          'Marketplace': 'Marketplace',
          'My Basket': 'My Basket',
          'My Account': 'My Account',
          'AppBar Search': 'Search',
          // HOMEPAGE
          'Posts': 'Posts',
          'Reels': 'Reels',
          'Homepage Share-1':
              'Share something about your company with your followers.',
          'Homepage Share-2': 'shared the post',
          'Homepage Share-3': 'Share',
          'Homepage Share-4': 'Sharing',
          'Like-1': 'Like',
          'Like-2': 'Liked',
          'Like-3': 'Liked',
          'Comment-1': 'Comment',
          'Comment-2': 'Comments',
          'Comment-3': 'Write a comment',
          'Save': 'Save',

        },
        'tr_TR': {
          // LANGUAGE PAGE
          'Language Selection': 'Dil Seçimi',
          'Save': 'Kaydet',
          // LOGIN PAGE
          'Member Login': 'Üye Girişi',
          'E-mail': 'E-mail',
          'Password': 'Şifre',
          'Remember me:': 'Beni hatırla',
          'Forgot Password': 'Şifremi Unuttum?',
          'Login': 'Giriş Yap',
          'Sign Up': 'Üye Ol',
          'About Us': 'Hakkımızda',
          'Privacy': 'Gizlilik',
          'Terms and Conditions': 'Kurallar ve Şartlar',
          'Contact': 'İletişim',
          'Copyright': 'Copright 2022 B2Geta. Tüm Hakları Saklıdır',
          'E-mail Validate-1': 'Lütfen e-mail adresinizi giriniz',
          'E-mail Validate-2': 'Lütfen geçerli bir email adresi giriniz',
          'Password Validate-1': 'Lütfen şifrenizi giriniz',
          'Password Validate-2': 'Şifre en az 8 karakter uzunluğunda olmalıdır',
          'Login Error': 'E-mail Veya Şifre Hatalı',
          'Close': 'Kapat',
          // REGISTER PAGE
          'Create Account': 'Hesap Oluştur',
          'E-mail (confirm)': 'E-mail (tekrar)',
          'Password (confirm)': 'Şifre (tekrar)',
          'Company Name': 'Firma Adı',
          'Official Person': 'Yetkili Kişi',
          'Official Phone': 'Yetkili Telefon',
          'Country': 'Ülke',
          "Country Dropdown": 'Ülke ara...',
          'User Agreement': 'Kullanıcı sözleşmesini okudum onaylıyorum',
          'E-mail Validate-3': 'Email adresleri uyuşmuyor',
          'Password Validate-3': 'Şifreler uyuşmuyor',
          'Company Name Validate': 'Lütfen firma adını giriniz',
          'Register Alert-1': 'Üyelik Başarılı',
          'Register Alert-2': 'Bilgilerinizi Kontrol Ediniz',
          // NAVIGATION PAGE
          'Homepage': 'Anasayfa',
          'Marketplace': 'Pazaryeri',
          'My Basket': 'Sepetim',
          'My Account': 'Hesabım',
          'AppBar Search': 'Aranacak kelimeyi giriniz',
          // HOMEPAGE
          'Posts': 'Postlar',
          'Reels': 'Reels',
          'Homepage Share-1': 'Firman hakkında takipçilerinle bir şeyler paylaş.',
          'Homepage Share-2': 'gönderi paylaştı.',
          'Homepage Share-3': 'Paylaş',
          'Homepage Share-4': 'Paylaşım',
          'Like-1': 'Beğen',
          'Like-2': 'Beğendin',
          'Like-3': 'Beğeni',
          'Comment-1': 'Yorum Yap',
          'Comment-2': 'Yorum',
          'Comment-3': 'Yorum yaz',
          'Save': 'Kaydet',
        },
        'de_DE': {
          // LANGUAGE PAGE
          'Language Selection': 'Sprachauswahl',
          'Save': 'Sparen',
        }
      };
}
