// ignore_for_file: public_member_api_docs, sort_constructors_first

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BrandModel {
/*
{
  "id": "2",
  "name": "Our Brand",
  "status": "private"
}
*/

  String? id;
  String? name;
  String? status;

  BrandModel({
    this.id,
    this.name,
    this.status,
  });
  BrandModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    status = json['status']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['status'] = status;
    return data;
  }

  @override
  bool operator ==(other) => other is BrandModel && name == other.name;

  @override
  int get hashCode => name.hashCode;
}
