///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductDetailModelCategories {
/*
{
  "id": "85",
  "product_id": "64",
  "category_id": "712",
  "category_name": "Kapı"
}
*/

  String? id;
  String? productId;
  String? categoryId;
  String? categoryName;

  ProductDetailModelCategories({
    this.id,
    this.productId,
    this.categoryId,
    this.categoryName,
  });
  ProductDetailModelCategories.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    productId = json['product_id']?.toString();
    categoryId = json['category_id']?.toString();
    categoryName = json['category_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['product_id'] = productId;
    data['category_id'] = categoryId;
    data['category_name'] = categoryName;
    return data;
  }
}

class ProductDetailModelBrand {
/*
{
  "id": "1",
  "name": "My Band"
}
*/

  String? id;
  String? name;

  ProductDetailModelBrand({
    this.id,
    this.name,
  });
  ProductDetailModelBrand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ProductDetailModel {
/*
{
  "id": "64",
  "account_id": "5",
  "user_id": "5",
  "product_name": "2",
  "product_description": "2",
  "product_summary": "2",
  "brand": {
    "id": "1",
    "name": "My Band"
  },
  "price": "222.00",
  "currency": "TRY",
  "status": "1",
  "categories": [
    {
      "id": "85",
      "product_id": "64",
      "category_id": "712",
      "category_name": "Kapı"
    }
  ],
  "images": [
    "https://api.businessucces.com/uploads/products/2023/03/21032023115627-1679396187.jpg"
  ]
}
*/

  String? id;
  String? accountId;
  String? userId;
  String? productName;
  String? productDescription;
  String? productSummary;
  ProductDetailModelBrand? brand;
  String? price;
  String? currency;
  String? status;
  List<ProductDetailModelCategories?>? categories;
  List<String?>? images;

  ProductDetailModel({
    this.id,
    this.accountId,
    this.userId,
    this.productName,
    this.productDescription,
    this.productSummary,
    this.brand,
    this.price,
    this.currency,
    this.status,
    this.categories,
    this.images,
  });
  ProductDetailModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    accountId = json['account_id']?.toString();
    userId = json['user_id']?.toString();
    productName = json['product_name']?.toString();
    productDescription = json['product_description']?.toString();
    productSummary = json['product_summary']?.toString();
    brand = (json['brand'] != false)
        ? ProductDetailModelBrand.fromJson(json['brand'])
        : null;
    price = json['price']?.toString();
    currency = json['currency']?.toString();
    status = json['status']?.toString();
    if (json['categories'] != null) {
      final v = json['categories'];
      final arr0 = <ProductDetailModelCategories>[];
      v.forEach((v) {
        arr0.add(ProductDetailModelCategories.fromJson(v));
      });
      categories = arr0;
    }
    if (json['images'] != null) {
      final v = json['images'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      images = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['account_id'] = accountId;
    data['user_id'] = userId;
    data['product_name'] = productName;
    data['product_description'] = productDescription;
    data['product_summary'] = productSummary;
    if (brand != null) {
      data['brand'] = brand!.toJson();
    }
    data['price'] = price;
    data['currency'] = currency;
    data['status'] = status;
    if (categories != null) {
      final v = categories;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['categories'] = arr0;
    }
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['images'] = arr0;
    }
    return data;
  }
}
