///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductDetailsModel {
/*
{
  "id": "1",
  "account_id": "5",
  "user_id": "5",
  "product_name": "Deneme Ürünü",
  "product_description": "Deneme Ürün  Açıklaması",
  "product_summary": "Deneme Ürün Özeti",
  "brand": false,
  "price": "100.00",
  "currency": "TRY",
  "status": "1",
  "categories": [
    ""
  ],
  "images": [
    "https://api.businessucces.com/uploads/products/2023/03/21032023115627-1679396187.jpg"
  ]
} 
*/

  String? id;
  String? accountId;
  String? userId;
  String? productName;
  String? productDescription;
  String? productSummary;
  bool? brand;
  String? price;
  String? currency;
  String? status;
  List<String?>? categories;
  List<String?>? images;

  ProductDetailsModel({
    this.id,
    this.accountId,
    this.userId,
    this.productName,
    this.productDescription,
    this.productSummary,
    this.brand,
    this.price,
    this.currency,
    this.status,
    this.categories,
    this.images,
  });
  ProductDetailsModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    accountId = json['account_id']?.toString();
    userId = json['user_id']?.toString();
    productName = json['product_name']?.toString();
    productDescription = json['product_description']?.toString();
    productSummary = json['product_summary']?.toString();
    brand = json['brand'];
    price = json['price']?.toString();
    currency = json['currency']?.toString();
    status = json['status']?.toString();
  if (json['categories'] != null) {
  final v = json['categories'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    categories = arr0;
    }
  if (json['images'] != null) {
  final v = json['images'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    images = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['account_id'] = accountId;
    data['user_id'] = userId;
    data['product_name'] = productName;
    data['product_description'] = productDescription;
    data['product_summary'] = productSummary;
    data['brand'] = brand;
    data['price'] = price;
    data['currency'] = currency;
    data['status'] = status;
    if (categories != null) {
      final v = categories;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['categories'] = arr0;
    }
    if (images != null) {
      final v = images;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['images'] = arr0;
    }
    return data;
  }
}
