///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductListModelDescription {
/*
{
  "en": "Test Product Description 2x2",
  "tr": "Deneme Ürün  Açıklaması 2x2",
  "de": "Deneme Ürün  Açıklaması 2x2"
} 
*/

  String? en;
  String? tr;
  String? de;

  ProductListModelDescription({
    this.en,
    this.tr,
    this.de,
  });
  ProductListModelDescription.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductListModelSummary {
/*
{
  "en": "Test Product Summary 2x2",
  "tr": "Deneme Ürün Özeti 2x2",
  "de": "Deneme Ürün Özeti 2x2"
} 
*/

  String? en;
  String? tr;
  String? de;

  ProductListModelSummary({
    this.en,
    this.tr,
    this.de,
  });
  ProductListModelSummary.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductListModelName {
/*
{
  "en": "Test Product 2x2",
  "tr": "Deneme Ürünü 2x2",
  "de": "Deneme Ürünü 2x2"
} 
*/

  String? en;
  String? tr;
  String? de;

  ProductListModelName({
    this.en,
    this.tr,
    this.de,
  });
  ProductListModelName.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductListModel {
/*
{
  "id": "3361",
  "product_type": "product",
  "name": {
    "en": "Test Product 2x2",
    "tr": "Deneme Ürünü 2x2",
    "de": "Deneme Ürünü 2x2"
  },
  "summary": {
    "en": "Test Product Summary 2x2",
    "tr": "Deneme Ürün Özeti 2x2",
    "de": "Deneme Ürün Özeti 2x2"
  },
  "description": {
    "en": "Test Product Description 2x2",
    "tr": "Deneme Ürün  Açıklaması 2x2",
    "de": "Deneme Ürün  Açıklaması 2x2"
  },
  "brand": false,
  "price": "2001.00",
  "currency": "USD",
  "images": [
    "https://api.businessucces.com/uploads/products/2022/12/11122022150140-1670767300.jpg"
  ]
} 
*/

  String? id;
  String? productType;
  ProductListModelName? name;
  ProductListModelSummary? summary;
  ProductListModelDescription? description;
  bool? brand;
  String? price;
  String? currency;
  List<String?>? images;

  ProductListModel({
    this.id,
    this.productType,
    this.name,
    this.summary,
    this.description,
    this.brand,
    this.price,
    this.currency,
    this.images,
  });
  ProductListModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    productType = json['product_type']?.toString();
    name = (json['name'] != null) ? ProductListModelName.fromJson(json['name']) : null;
    summary = (json['summary'] != null) ? ProductListModelSummary.fromJson(json['summary']) : null;
    description = (json['description'] != null) ? ProductListModelDescription.fromJson(json['description']) : null;
    brand = json['brand'];
    price = json['price']?.toString();
    currency = json['currency']?.toString();
  if (json['images'] != null) {
  final v = json['images'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    images = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['product_type'] = productType;
    if (name != null) {
      data['name'] = name!.toJson();
    }
    if (summary != null) {
      data['summary'] = summary!.toJson();
    }
    if (description != null) {
      data['description'] = description!.toJson();
    }
    data['brand'] = brand;
    data['price'] = price;
    data['currency'] = currency;
    if (images != null) {
      final v = images;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v);
  }
      data['images'] = arr0;
    }
    return data;
  }
}
