///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductModelSeller {
/*
{
  "id": "133",
  "type": "company",
  "username": "user_133",
  "name": "Center Tekstil",
  "photo": "https://api.businessucces.com/uploads/logos/2023/04/03042023203301-1680543181.png",
  "cover": ""
} 
*/

  String? id;
  String? type;
  String? username;
  String? name;
  String? photo;
  String? cover;

  ProductModelSeller({
    this.id,
    this.type,
    this.username,
    this.name,
    this.photo,
    this.cover,
  });
  ProductModelSeller.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    type = json['type']?.toString();
    username = json['username']?.toString();
    name = json['name']?.toString();
    photo = json['photo']?.toString();
    cover = json['cover']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['type'] = type;
    data['username'] = username;
    data['name'] = name;
    data['photo'] = photo;
    data['cover'] = cover;
    return data;
  }
}

class ProductModelBrand {
/*
{
  "id": "1",
  "name": "My Band"
} 
*/

  String? id;
  String? name;

  ProductModelBrand({
    this.id,
    this.name,
  });
  ProductModelBrand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ProductModelDescription {
/*
{
  "en": "<figure class=\"table\"><table><tbody><tr><td><ul><li>Ürün Teknik Özellikleri 20mm hav yüksekliğinde modern bilgisayarlı tezgahlarda dokunmaktadır.<br>&nbsp;</li><li>Birim metre kare ağırlığı ortalama 2300 gr/m² dir.<br>&nbsp;</li><li>Halılarımızda kullanan hav ipliği 1. sınıfdır , (hav, tüy çıkartmaz) olduğundan keçeleşme yapmaz.<br>&nbsp;</li><li>Sıkı ve tok dokuması sayesinde yaz-kış kullanabilirsiniz.<br>&nbsp;</li><li>Ekstra yumuşatıcı ile üretilmiş olan hav ipliğimiz sayesinden ayakaltı konforu sağlar.<br>&nbsp;</li><li>Yumuşak bir dokuya sahiptir.<br>&nbsp;</li><li>Hav çıkarmaz.<br>&nbsp;</li><li>Kolay temizlenir.<br>&nbsp;</li><li>Kullanıldığı alanda toz üretmez.<br>&nbsp;</li><li>Ürünlerimiz profesyonel ekipler tarafından üretilerek paket edilip siz değerli müşterilerimize sunulmaktadır.<br>&nbsp;</li><li>Ürünler görseller ile birebir aynıdır.</li></ul></td></tr></tbody></table></figure>",
  "tr": "<figure class=\"table\"><table><tbody><tr><td><ul><li>Ürün Teknik Özellikleri 20mm hav yüksekliğinde modern bilgisayarlı tezgahlarda dokunmaktadır.<br>&nbsp;</li><li>Birim metre kare ağırlığı ortalama 2300 gr/m² dir.<br>&nbsp;</li><li>Halılarımızda kullanan hav ipliği 1. sınıfdır , (hav, tüy çıkartmaz) olduğundan keçeleşme yapmaz.<br>&nbsp;</li><li>Sıkı ve tok dokuması sayesinde yaz-kış kullanabilirsiniz.<br>&nbsp;</li><li>Ekstra yumuşatıcı ile üretilmiş olan hav ipliğimiz sayesinden ayakaltı konforu sağlar.<br>&nbsp;</li><li>Yumuşak bir dokuya sahiptir.<br>&nbsp;</li><li>Hav çıkarmaz.<br>&nbsp;</li><li>Kolay temizlenir.<br>&nbsp;</li><li>Kullanıldığı alanda toz üretmez.<br>&nbsp;</li><li>Ürünlerimiz profesyonel ekipler tarafından üretilerek paket edilip siz değerli müşterilerimize sunulmaktadır.<br>&nbsp;</li><li>Ürünler görseller ile birebir aynıdır.</li></ul></td></tr></tbody></table></figure>",
  "de": "<figure class=\"table\"><table><tbody><tr><td><ul><li>Ürün Teknik Özellikleri 20mm hav yüksekliğinde modern bilgisayarlı tezgahlarda dokunmaktadır.<br>&nbsp;</li><li>Birim metre kare ağırlığı ortalama 2300 gr/m² dir.<br>&nbsp;</li><li>Halılarımızda kullanan hav ipliği 1. sınıfdır , (hav, tüy çıkartmaz) olduğundan keçeleşme yapmaz.<br>&nbsp;</li><li>Sıkı ve tok dokuması sayesinde yaz-kış kullanabilirsiniz.<br>&nbsp;</li><li>Ekstra yumuşatıcı ile üretilmiş olan hav ipliğimiz sayesinden ayakaltı konforu sağlar.<br>&nbsp;</li><li>Yumuşak bir dokuya sahiptir.<br>&nbsp;</li><li>Hav çıkarmaz.<br>&nbsp;</li><li>Kolay temizlenir.<br>&nbsp;</li><li>Kullanıldığı alanda toz üretmez.<br>&nbsp;</li><li>Ürünlerimiz profesyonel ekipler tarafından üretilerek paket edilip siz değerli müşterilerimize sunulmaktadır.<br>&nbsp;</li><li>Ürünler görseller ile birebir aynıdır.</li></ul></td></tr></tbody></table></figure>"
} 
*/

  String? en;
  String? tr;
  String? de;

  ProductModelDescription({
    this.en,
    this.tr,
    this.de,
  });
  ProductModelDescription.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductModelSummary {
/*
{
  "en": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı",
  "tr": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı",
  "de": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı"
} 
*/

  String? en;
  String? tr;
  String? de;

  ProductModelSummary({
    this.en,
    this.tr,
    this.de,
  });
  ProductModelSummary.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductModelName {
/*
{
  "en": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı",
  "tr": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı",
  "de": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı"
} 
*/

  String? en;
  String? tr;
  String? de;

  ProductModelName({
    this.en,
    this.tr,
    this.de,
  });
  ProductModelName.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductModel {
/*
{
  "id": "113",
  "product_type": "",
  "account_id": "133",
  "name": {
    "en": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı",
    "tr": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı",
    "de": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı"
  },
  "summary": {
    "en": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı",
    "tr": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı",
    "de": "Beyaz Bej Bukleli Yumuşak Peluş Shaggy Dokuma Çocuk Odası Oturma Odası Salon Mutfak Halısı"
  },
  "description": {
    "en": "<figure class=\"table\"><table><tbody><tr><td><ul><li>Ürün Teknik Özellikleri 20mm hav yüksekliğinde modern bilgisayarlı tezgahlarda dokunmaktadır.<br>&nbsp;</li><li>Birim metre kare ağırlığı ortalama 2300 gr/m² dir.<br>&nbsp;</li><li>Halılarımızda kullanan hav ipliği 1. sınıfdır , (hav, tüy çıkartmaz) olduğundan keçeleşme yapmaz.<br>&nbsp;</li><li>Sıkı ve tok dokuması sayesinde yaz-kış kullanabilirsiniz.<br>&nbsp;</li><li>Ekstra yumuşatıcı ile üretilmiş olan hav ipliğimiz sayesinden ayakaltı konforu sağlar.<br>&nbsp;</li><li>Yumuşak bir dokuya sahiptir.<br>&nbsp;</li><li>Hav çıkarmaz.<br>&nbsp;</li><li>Kolay temizlenir.<br>&nbsp;</li><li>Kullanıldığı alanda toz üretmez.<br>&nbsp;</li><li>Ürünlerimiz profesyonel ekipler tarafından üretilerek paket edilip siz değerli müşterilerimize sunulmaktadır.<br>&nbsp;</li><li>Ürünler görseller ile birebir aynıdır.</li></ul></td></tr></tbody></table></figure>",
    "tr": "<figure class=\"table\"><table><tbody><tr><td><ul><li>Ürün Teknik Özellikleri 20mm hav yüksekliğinde modern bilgisayarlı tezgahlarda dokunmaktadır.<br>&nbsp;</li><li>Birim metre kare ağırlığı ortalama 2300 gr/m² dir.<br>&nbsp;</li><li>Halılarımızda kullanan hav ipliği 1. sınıfdır , (hav, tüy çıkartmaz) olduğundan keçeleşme yapmaz.<br>&nbsp;</li><li>Sıkı ve tok dokuması sayesinde yaz-kış kullanabilirsiniz.<br>&nbsp;</li><li>Ekstra yumuşatıcı ile üretilmiş olan hav ipliğimiz sayesinden ayakaltı konforu sağlar.<br>&nbsp;</li><li>Yumuşak bir dokuya sahiptir.<br>&nbsp;</li><li>Hav çıkarmaz.<br>&nbsp;</li><li>Kolay temizlenir.<br>&nbsp;</li><li>Kullanıldığı alanda toz üretmez.<br>&nbsp;</li><li>Ürünlerimiz profesyonel ekipler tarafından üretilerek paket edilip siz değerli müşterilerimize sunulmaktadır.<br>&nbsp;</li><li>Ürünler görseller ile birebir aynıdır.</li></ul></td></tr></tbody></table></figure>",
    "de": "<figure class=\"table\"><table><tbody><tr><td><ul><li>Ürün Teknik Özellikleri 20mm hav yüksekliğinde modern bilgisayarlı tezgahlarda dokunmaktadır.<br>&nbsp;</li><li>Birim metre kare ağırlığı ortalama 2300 gr/m² dir.<br>&nbsp;</li><li>Halılarımızda kullanan hav ipliği 1. sınıfdır , (hav, tüy çıkartmaz) olduğundan keçeleşme yapmaz.<br>&nbsp;</li><li>Sıkı ve tok dokuması sayesinde yaz-kış kullanabilirsiniz.<br>&nbsp;</li><li>Ekstra yumuşatıcı ile üretilmiş olan hav ipliğimiz sayesinden ayakaltı konforu sağlar.<br>&nbsp;</li><li>Yumuşak bir dokuya sahiptir.<br>&nbsp;</li><li>Hav çıkarmaz.<br>&nbsp;</li><li>Kolay temizlenir.<br>&nbsp;</li><li>Kullanıldığı alanda toz üretmez.<br>&nbsp;</li><li>Ürünlerimiz profesyonel ekipler tarafından üretilerek paket edilip siz değerli müşterilerimize sunulmaktadır.<br>&nbsp;</li><li>Ürünler görseller ile birebir aynıdır.</li></ul></td></tr></tbody></table></figure>"
  },
  "brand": {
    "id": "1",
    "name": "My Band"
  },
  "price": "1.56",
  "currency": "TRY",
  "images": [
    "https://api.businessucces.com/uploads/products/2023/04/03042023204559-1680543959.jpg"
  ],
  "seller": {
    "id": "133",
    "type": "company",
    "username": "user_133",
    "name": "Center Tekstil",
    "photo": "https://api.businessucces.com/uploads/logos/2023/04/03042023203301-1680543181.png",
    "cover": ""
  }
} 
*/

  String? id;
  String? productType;
  String? accountId;
  ProductModelName? name;
  ProductModelSummary? summary;
  ProductModelDescription? description;
  ProductModelBrand? brand;
  String? price;
  String? currency;
  List<Images>? images;
  ProductModelSeller? seller;

  ProductModel({
    this.id,
    this.productType,
    this.accountId,
    this.name,
    this.summary,
    this.description,
    this.brand,
    this.price,
    this.currency,
    this.images,
    this.seller,
  });
  ProductModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    productType = json['product_type']?.toString();
    accountId = json['account_id']?.toString();
    name =
        (json['name'] != null) ? ProductModelName.fromJson(json['name']) : null;
    summary = (json['summary'] != null)
        ? ProductModelSummary.fromJson(json['summary'])
        : null;
    description = (json['description'] != null)
        ? ProductModelDescription.fromJson(json['description'])
        : null;
    brand = (json['brand'] != null)
        ? ProductModelBrand.fromJson(json['brand'])
        : null;
    price = json['price']?.toString();
    currency = json['currency']?.toString();
    images = json["images"] == null
        ? []
        : List<Images>.from(json["images"]!.map((x) => Images.fromJson(x)));
    seller = (json['seller'] != null)
        ? ProductModelSeller.fromJson(json['seller'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['product_type'] = productType;
    data['account_id'] = accountId;
    if (name != null) {
      data['name'] = name!.toJson();
    }
    if (summary != null) {
      data['summary'] = summary!.toJson();
    }
    if (description != null) {
      data['description'] = description!.toJson();
    }
    if (brand != null) {
      data['brand'] = brand!.toJson();
    }
    data['price'] = price;
    data['currency'] = currency;
    if (images != null) {
      final v = images;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['images'] = arr0;
    }
    if (seller != null) {
      data['seller'] = seller!.toJson();
    }
    return data;
  }
}

class Images {
/*
{
  "id": "421",
  "url": "https://api.businessucces.com/uploads/products/2023/11/04112023191741-1699114661.png",
  "product_id": "474",
  "file": "uploads/products/2023/11/04112023191741-1699114661.png"
} 
*/

  String? id;
  String? url;
  String? productId;
  String? file;

  Images({
    this.id,
    this.url,
    this.productId,
    this.file,
  });
  Images.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    url = json['url']?.toString();
    productId = json['product_id']?.toString();
    file = json['file']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['url'] = url;
    data['product_id'] = productId;
    data['file'] = file;
    return data;
  }
}
