///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductModelBrand {
/*
{
  "id": "1",
  "name": "My Band"
}
*/

  String? id;
  String? name;

  ProductModelBrand({
    this.id,
    this.name,
  });
  ProductModelBrand.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class ProductModelDescription {
/*
{
  "en": "Test Product Description",
  "tr": "Deneme Ürün  Açıklaması",
  "de": "Deneme Ürün  Açıklaması"
}
*/

  String? en;
  String? tr;
  String? de;

  ProductModelDescription({
    this.en,
    this.tr,
    this.de,
  });
  ProductModelDescription.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductModelSummary {
/*
{
  "en": "Test Product Summary",
  "tr": "Deneme Ürün Özeti",
  "de": "Deneme Ürün Özeti"
}
*/

  String? en;
  String? tr;
  String? de;

  ProductModelSummary({
    this.en,
    this.tr,
    this.de,
  });
  ProductModelSummary.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductModelName {
/*
{
  "en": "Test Product",
  "tr": "Deneme Ürünü",
  "de": "Deneme Ürünü"
}
*/

  String? en;
  String? tr;
  String? de;

  ProductModelName({
    this.en,
    this.tr,
    this.de,
  });
  ProductModelName.fromJson(Map<String, dynamic> json) {
    en = json['en']?.toString();
    tr = json['tr']?.toString();
    de = json['de']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['en'] = en;
    data['tr'] = tr;
    data['de'] = de;
    return data;
  }
}

class ProductModel {
/*
{
  "id": "1",
  "product_type": "",
  "name": {
    "en": "Test Product",
    "tr": "Deneme Ürünü",
    "de": "Deneme Ürünü"
  },
  "summary": {
    "en": "Test Product Summary",
    "tr": "Deneme Ürün Özeti",
    "de": "Deneme Ürün Özeti"
  },
  "description": {
    "en": "Test Product Description",
    "tr": "Deneme Ürün  Açıklaması",
    "de": "Deneme Ürün  Açıklaması"
  },
  "brand": {
    "id": "1",
    "name": "My Band"
  },
  "price": "100.00",
  "currency": "TRY",
  "images": [
    "https://api.businessucces.com/uploads/products/2023/03/21032023115627-1679396187.jpg"
  ]
}
*/

  String? id;
  String? productType;
  ProductModelName? name;
  ProductModelSummary? summary;
  ProductModelDescription? description;
  ProductModelBrand? brand;
  String? price;
  String? currency;
  List<String?>? images;

  ProductModel({
    this.id,
    this.productType,
    this.name,
    this.summary,
    this.description,
    this.brand,
    this.price,
    this.currency,
    this.images,
  });
  ProductModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    productType = json['product_type']?.toString();
    name =
        (json['name'] != null) ? ProductModelName.fromJson(json['name']) : null;
    summary = (json['summary'] != null)
        ? ProductModelSummary.fromJson(json['summary'])
        : null;
    description = (json['description'] != null)
        ? ProductModelDescription.fromJson(json['description'])
        : null;
    brand = (json['brand'] != false)
        ? ProductModelBrand.fromJson(json['brand'])
        : null;
    price = json['price']?.toString();
    currency = json['currency']?.toString();
    if (json['images'] != null) {
      final v = json['images'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      images = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['product_type'] = productType;
    if (name != null) {
      data['name'] = name!.toJson();
    }
    if (summary != null) {
      data['summary'] = summary!.toJson();
    }
    if (description != null) {
      data['description'] = description!.toJson();
    }
    if (brand != null) {
      data['brand'] = brand!.toJson();
    }
    data['price'] = price;
    data['currency'] = currency;
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['images'] = arr0;
    }
    return data;
  }
}
