///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyFollowingModel {
/*
{
  "user_id": "62",
  "following_id": "57",
  "following_type": "personal",
  "follow_date": "2023-03-22 12:37:13",
  "is_approve": "1",
  "user_user_type": "personal",
  "user_firstname": "Yusuf Efe",
  "user_lastname": "Elbasan",
  "user_company_name": "",
  "following_user_type": "personal",
  "following_firstname": "Hazal ",
  "following_lastname": "Bilginer",
  "following_company_name": ""
}
*/

  String? userId;
  String? followingId;
  String? followingType;
  String? followDate;
  String? isApprove;
  String? userUserType;
  String? userFirstname;
  String? userLastname;
  String? userCompanyName;
  String? followingUserType;
  String? followingFirstname;
  String? followingLastname;
  String? followingCompanyName;

  MyFollowingModel({
    this.userId,
    this.followingId,
    this.followingType,
    this.followDate,
    this.isApprove,
    this.userUserType,
    this.userFirstname,
    this.userLastname,
    this.userCompanyName,
    this.followingUserType,
    this.followingFirstname,
    this.followingLastname,
    this.followingCompanyName,
  });
  MyFollowingModel.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toString();
    followingId = json['following_id']?.toString();
    followingType = json['following_type']?.toString();
    followDate = json['follow_date']?.toString();
    isApprove = json['is_approve']?.toString();
    userUserType = json['user_user_type']?.toString();
    userFirstname = json['user_firstname']?.toString();
    userLastname = json['user_lastname']?.toString();
    userCompanyName = json['user_company_name']?.toString();
    followingUserType = json['following_user_type']?.toString();
    followingFirstname = json['following_firstname']?.toString();
    followingLastname = json['following_lastname']?.toString();
    followingCompanyName = json['following_company_name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['following_id'] = followingId;
    data['following_type'] = followingType;
    data['follow_date'] = followDate;
    data['is_approve'] = isApprove;
    data['user_user_type'] = userUserType;
    data['user_firstname'] = userFirstname;
    data['user_lastname'] = userLastname;
    data['user_company_name'] = userCompanyName;
    data['following_user_type'] = followingUserType;
    data['following_firstname'] = followingFirstname;
    data['following_lastname'] = followingLastname;
    data['following_company_name'] = followingCompanyName;
    return data;
  }
}
