///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MyFollowerModel {
/*
{
  "user_id": "1",
  "following_id": "13",
  "following_type": "personal",
  "follow_date": "2023-03-26 21:40:55",
  "is_approve": "1",
  "user_user_type": "personal",
  "user_firstname": "Mehmet",
  "user_lastname": "Can",
  "user_company_name": "",
  "user_photo": "https://api.businessucces.com/uploads/profile/2023/03/20032023122543-1679311543.jpg",
  "user_cover": "",
  "following_user_type": "personal",
  "following_firstname": "Enes",
  "following_lastname": "ALTUN",
  "following_company_name": "",
  "following_avatar": "https://api.businessucces.com/uploads/profile/2023/03/14032023193017-1678818617.jpg",
  "following_cover": ""
}
*/

  String? userId;
  String? followingId;
  String? followingType;
  String? followDate;
  String? isApprove;
  String? userUserType;
  String? userFirstname;
  String? userLastname;
  String? userCompanyName;
  String? userPhoto;
  String? userCover;
  String? followingUserType;
  String? followingFirstname;
  String? followingLastname;
  String? followingCompanyName;
  String? followingAvatar;
  String? followingCover;

  MyFollowerModel({
    this.userId,
    this.followingId,
    this.followingType,
    this.followDate,
    this.isApprove,
    this.userUserType,
    this.userFirstname,
    this.userLastname,
    this.userCompanyName,
    this.userPhoto,
    this.userCover,
    this.followingUserType,
    this.followingFirstname,
    this.followingLastname,
    this.followingCompanyName,
    this.followingAvatar,
    this.followingCover,
  });
  MyFollowerModel.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toString();
    followingId = json['following_id']?.toString();
    followingType = json['following_type']?.toString();
    followDate = json['follow_date']?.toString();
    isApprove = json['is_approve']?.toString();
    userUserType = json['user_user_type']?.toString();
    userFirstname = json['user_firstname']?.toString();
    userLastname = json['user_lastname']?.toString();
    userCompanyName = json['user_company_name']?.toString();
    userPhoto = json['user_photo']?.toString();
    userCover = json['user_cover']?.toString();
    followingUserType = json['following_user_type']?.toString();
    followingFirstname = json['following_firstname']?.toString();
    followingLastname = json['following_lastname']?.toString();
    followingCompanyName = json['following_company_name']?.toString();
    followingAvatar = json['following_avatar']?.toString();
    followingCover = json['following_cover']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['following_id'] = followingId;
    data['following_type'] = followingType;
    data['follow_date'] = followDate;
    data['is_approve'] = isApprove;
    data['user_user_type'] = userUserType;
    data['user_firstname'] = userFirstname;
    data['user_lastname'] = userLastname;
    data['user_company_name'] = userCompanyName;
    data['user_photo'] = userPhoto;
    data['user_cover'] = userCover;
    data['following_user_type'] = followingUserType;
    data['following_firstname'] = followingFirstname;
    data['following_lastname'] = followingLastname;
    data['following_company_name'] = followingCompanyName;
    data['following_avatar'] = followingAvatar;
    data['following_cover'] = followingCover;
    return data;
  }
}
