///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CompanyProfileModelCollaborator {
/*
{
  "id": "57",
  "role": "admin",
  "name": "Mehmet Can",
  "photo": "https://api.businessucces.com/uploads/profile/2023/03/03032023112546-1677839146.jpg"
} 
*/

  String? id;
  String? role;
  String? name;
  String? photo;

  CompanyProfileModelCollaborator({
    this.id,
    this.role,
    this.name,
    this.photo,
  });
  CompanyProfileModelCollaborator.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    role = json['role']?.toString();
    name = json['name']?.toString();
    photo = json['photo']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['role'] = role;
    data['name'] = name;
    data['photo'] = photo;
    return data;
  }
}

class CompanyProfileModelSettings {
/*
{
  "language": "tr",
  "country": "TR",
  "timezone": "3.00"
} 
*/

  String? language;
  String? country;
  String? timezone;

  CompanyProfileModelSettings({
    this.language,
    this.country,
    this.timezone,
  });
  CompanyProfileModelSettings.fromJson(Map<String, dynamic> json) {
    language = json['language']?.toString();
    country = json['country']?.toString();
    timezone = json['timezone']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['language'] = language;
    data['country'] = country;
    data['timezone'] = timezone;
    return data;
  }
}

class CompanyProfileModelDistrict {
/*
{
  "id": "45",
  "name": "Reef Al Fujairah City"
} 
*/

  String? id;
  String? name;

  CompanyProfileModelDistrict({
    this.id,
    this.name,
  });
  CompanyProfileModelDistrict.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class CompanyProfileModelCity {
/*
{
  "id": "34",
  "name": "Kunene Region"
} 
*/

  String? id;
  String? name;

  CompanyProfileModelCity({
    this.id,
    this.name,
  });
  CompanyProfileModelCity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class CompanyProfileModelCountryTimezones {
/*
{
  "zoneName": "Europe/Istanbul",
  "gmtOffset": 10800,
  "gmtOffsetName": "UTC+03:00",
  "abbreviation": "EET",
  "tzName": "Eastern European Time"
} 
*/

  String? zoneName;
  int? gmtOffset;
  String? gmtOffsetName;
  String? abbreviation;
  String? tzName;

  CompanyProfileModelCountryTimezones({
    this.zoneName,
    this.gmtOffset,
    this.gmtOffsetName,
    this.abbreviation,
    this.tzName,
  });
  CompanyProfileModelCountryTimezones.fromJson(Map<String, dynamic> json) {
    zoneName = json['zoneName']?.toString();
    gmtOffset = json['gmtOffset']?.toInt();
    gmtOffsetName = json['gmtOffsetName']?.toString();
    abbreviation = json['abbreviation']?.toString();
    tzName = json['tzName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['zoneName'] = zoneName;
    data['gmtOffset'] = gmtOffset;
    data['gmtOffsetName'] = gmtOffsetName;
    data['abbreviation'] = abbreviation;
    data['tzName'] = tzName;
    return data;
  }
}

class CompanyProfileModelCountry {
/*
{
  "id": "225",
  "name": "Turkey",
  "code": "TR",
  "phonecode": "90",
  "currency": "TRY",
  "currency_name": "Turkish lira",
  "currency_symbol": "₺",
  "timezones": [
    {
      "zoneName": "Europe/Istanbul",
      "gmtOffset": 10800,
      "gmtOffsetName": "UTC+03:00",
      "abbreviation": "EET",
      "tzName": "Eastern European Time"
    }
  ],
  "flag": "🇹🇷"
} 
*/

  String? id;
  String? name;
  String? code;
  String? phonecode;
  String? currency;
  String? currencyName;
  String? currencySymbol;
  List<CompanyProfileModelCountryTimezones?>? timezones;
  String? flag;

  CompanyProfileModelCountry({
    this.id,
    this.name,
    this.code,
    this.phonecode,
    this.currency,
    this.currencyName,
    this.currencySymbol,
    this.timezones,
    this.flag,
  });
  CompanyProfileModelCountry.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    code = json['code']?.toString();
    phonecode = json['phonecode']?.toString();
    currency = json['currency']?.toString();
    currencyName = json['currency_name']?.toString();
    currencySymbol = json['currency_symbol']?.toString();
  if (json['timezones'] != null) {
  final v = json['timezones'];
  final arr0 = <CompanyProfileModelCountryTimezones>[];
  v.forEach((v) {
  arr0.add(CompanyProfileModelCountryTimezones.fromJson(v));
  });
    timezones = arr0;
    }
    flag = json['flag']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['code'] = code;
    data['phonecode'] = phonecode;
    data['currency'] = currency;
    data['currency_name'] = currencyName;
    data['currency_symbol'] = currencySymbol;
    if (timezones != null) {
      final v = timezones;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['timezones'] = arr0;
    }
    data['flag'] = flag;
    return data;
  }
}

class CompanyProfileModel {
/*
{
  "id": "97",
  "name": "ABC Firma LTD updated",
  "tax_office": "Beşiktaş",
  "tax_number": "1234567890",
  "phone": "+905556667788",
  "email": "example@company.com",
  "country": {
    "id": "225",
    "name": "Turkey",
    "code": "TR",
    "phonecode": "90",
    "currency": "TRY",
    "currency_name": "Turkish lira",
    "currency_symbol": "₺",
    "timezones": [
      {
        "zoneName": "Europe/Istanbul",
        "gmtOffset": 10800,
        "gmtOffsetName": "UTC+03:00",
        "abbreviation": "EET",
        "tzName": "Eastern European Time"
      }
    ],
    "flag": "🇹🇷"
  },
  "city": {
    "id": "34",
    "name": "Kunene Region"
  },
  "district": {
    "id": "45",
    "name": "Reef Al Fujairah City"
  },
  "address": "Mecidiyeköy mah abc sokak",
  "postal_code": "34387",
  "logo": "",
  "cover": "",
  "about": "Firma hakkında bilgiler",
  "settings": {
    "language": "tr",
    "country": "TR",
    "timezone": "3.00"
  },
  "registration_date": "2022-12-21 13:46:02",
  "collaborator": [
    {
      "id": "57",
      "role": "admin",
      "name": "Mehmet Can",
      "photo": "https://api.businessucces.com/uploads/profile/2023/03/03032023112546-1677839146.jpg"
    }
  ]
} 
*/

  String? id;
  String? name;
  String? taxOffice;
  String? taxNumber;
  String? phone;
  String? email;
  CompanyProfileModelCountry? country;
  CompanyProfileModelCity? city;
  CompanyProfileModelDistrict? district;
  String? address;
  String? postalCode;
  String? logo;
  String? cover;
  String? about;
  CompanyProfileModelSettings? settings;
  String? registrationDate;
  List<CompanyProfileModelCollaborator?>? collaborator;

  CompanyProfileModel({
    this.id,
    this.name,
    this.taxOffice,
    this.taxNumber,
    this.phone,
    this.email,
    this.country,
    this.city,
    this.district,
    this.address,
    this.postalCode,
    this.logo,
    this.cover,
    this.about,
    this.settings,
    this.registrationDate,
    this.collaborator,
  });
  CompanyProfileModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    taxOffice = json['tax_office']?.toString();
    taxNumber = json['tax_number']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    country = (json['country'] != null) ? CompanyProfileModelCountry.fromJson(json['country']) : null;
    city = (json['city'] != null) ? CompanyProfileModelCity.fromJson(json['city']) : null;
    district = (json['district'] != null) ? CompanyProfileModelDistrict.fromJson(json['district']) : null;
    address = json['address']?.toString();
    postalCode = json['postal_code']?.toString();
    logo = json['logo']?.toString();
    cover = json['cover']?.toString();
    about = json['about']?.toString();
    settings = (json['settings'] != null) ? CompanyProfileModelSettings.fromJson(json['settings']) : null;
    registrationDate = json['registration_date']?.toString();
  if (json['collaborator'] != null) {
  final v = json['collaborator'];
  final arr0 = <CompanyProfileModelCollaborator>[];
  v.forEach((v) {
  arr0.add(CompanyProfileModelCollaborator.fromJson(v));
  });
    collaborator = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['tax_office'] = taxOffice;
    data['tax_number'] = taxNumber;
    data['phone'] = phone;
    data['email'] = email;
    if (country != null) {
      data['country'] = country!.toJson();
    }
    if (city != null) {
      data['city'] = city!.toJson();
    }
    if (district != null) {
      data['district'] = district!.toJson();
    }
    data['address'] = address;
    data['postal_code'] = postalCode;
    data['logo'] = logo;
    data['cover'] = cover;
    data['about'] = about;
    if (settings != null) {
      data['settings'] = settings!.toJson();
    }
    data['registration_date'] = registrationDate;
    if (collaborator != null) {
      final v = collaborator;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['collaborator'] = arr0;
    }
    return data;
  }
}
